# RT-Thread building script for component

from building import *

src = Glob('*.c') 

cwd     = GetCurrentDir()
CPPPATH = [cwd]

group = DefineGroup('kpu3', src, depend = [''], CPPPATH = CPPPATH)

objs = [group]

list = os.listdir(cwd)

for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
