from building import *

# The set of source files associated with this SConscript file.
src = Split('''
main.c
mnt.c
''')

cwd     = GetCurrentDir()
CPPPATH = [cwd]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
