cd "d:/Kendryte_IDE/Project/lcd_image_LVGL/build"
SET ACTEL_FOR_ALTIUM_OVERRIDE= 
SET ALLUSERSPROFILE=C:\ProgramData
SET ALTERA_FOR_ALTIUM_OVERRIDE= 
SET APPDATA=C:\Users\QingYeMuRong\AppData\Roaming
SET CommonProgramFiles=C:\Program Files\Common Files
SET CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
SET CommonProgramW6432=C:\Program Files\Common Files
SET COMPUTERNAME=QINGYEMURONG
SET ComSpec=C:\Windows\system32\cmd.exe
SET DriverData=C:\Windows\System32\Drivers\DriverData
SET FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
SET FPS_BROWSER_USER_PROFILE_STRING=Default
SET HOMEDRIVE=C:
SET HOMEPATH=\Users\QingYeMuRong
SET LOCALAPPDATA=C:\Users\QingYeMuRong\AppData\Local
SET LOGONSERVER=\\QINGYEMURONG
SET NUMBER_OF_PROCESSORS=8
SET OneDrive=C:\Users\QingYeMuRong\OneDrive
SET OS=Windows_NT
SET Path=d:\Kendryte_IDE\KendryteIDE\bin;d:\Kendryte_IDE\KendryteIDE\LocalPackage\toolchain\bin;d:\Kendryte_IDE\KendryteIDE\LocalPackage\cmake\bin;d:\Kendryte_IDE\KendryteIDE\LocalPackage\jlink;d:\Kendryte_IDE\KendryteIDE\LocalPackage\clang-format\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH
SET PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
SET PROCESSOR_ARCHITECTURE=AMD64
SET PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
SET PROCESSOR_LEVEL=6
SET PROCESSOR_REVISION=8e0a
SET ProgramData=C:\ProgramData
SET ProgramFiles=C:\Program Files
SET ProgramFiles(x86)=C:\Program Files (x86)
SET ProgramW6432=C:\Program Files
SET PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
SET PUBLIC=C:\Users\Public
SET SESSIONNAME=Console
SET SystemDrive=C:
SET SystemRoot=C:\Windows
SET TEMP=C:\Users\QINGYE~1\AppData\Local\Temp
SET TMP=C:\Users\QINGYE~1\AppData\Local\Temp
SET USERDOMAIN=QINGYEMURONG
SET USERDOMAIN_ROAMINGPROFILE=QINGYEMURONG
SET USERNAME=QingYeMuRong
SET USERPROFILE=C:\Users\QingYeMuRong
SET VSCODE_CWD=D:\Kendryte_IDE\KendryteIDE\Application\app_1.34.1-beta_20190802.2
SET VSCODE_IPC_HOOK=\\.\pipe\c18c9f91769b1e7cba9ec541f132cfed-1.34.1-beta-main-sock
SET VSCODE_LOGS=D:\Kendryte_IDE\KendryteIDE\UserData\latest\user-data\logs\20201126T141421
SET VSCODE_NLS_CONFIG={"locale":"zh-cn","availableLanguages":{"*":"zh-cn"},"_languagePackId":"2ae16f5a9a23c98b985a67d503c3ac22.zh-cn","_translationsConfigFile":"D:\\Kendryte_IDE\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn\\tcf.json","_cacheRoot":"D:\\Kendryte_IDE\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn","_resolvedLanguagePackCoreLocation":"D:\\Kendryte_IDE\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn\\e4de46724de34a5f46541818e9fee25971ac9969","_corruptedFile":"D:\\Kendryte_IDE\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn\\corrupted.info","_languagePackSupport":true}
SET VSCODE_NODE_CACHED_DATA_DIR=D:\Kendryte_IDE\KendryteIDE\UserData\latest\user-data\CachedData\e4de46724de34a5f46541818e9fee25971ac9969
SET VSCODE_PID=2028
SET VSCODE_PORTABLE=D:\Kendryte_IDE\KendryteIDE\UserData\latest
SET windir=C:\Windows
SET PYTHONHOME=d:/Kendryte_IDE/KendryteIDE/LocalPackage/python2library
SET PYTHONPATH=d:/Kendryte_IDE/KendryteIDE/LocalPackage/python2library;d:/Kendryte_IDE/KendryteIDE/LocalPackage/toolchain/share/gdb/python
SET PYTHONDONTWRITEBYTECODE=yes
SET CMAKE_MAKE_PROGRAM=make
SET KENDRYTE_IDE=yes
SET LANG=en_US.utf-8
"d:/Kendryte_IDE/KendryteIDE/LocalPackage/cmake/bin/cmake.exe" --build d:/Kendryte_IDE/Project/lcd_image_LVGL/build -- -j 7